spring.graphql.graphiql.enabled=false
springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false

server.error.include-message=never
server.error.include-stacktrace=never
server.error.include-binding-errors=never
